set:
  base: bdpool
  type: .ks
  outtype: .txt
  fr: en
  to: zh
  start: 0
  row: 1
  path: C:\git\github\translatego\
  output: C:\git\github\translatetemp\
  compath: C:\git\github\translatecompound\

bdpool:
  amount: 1
  appid0: 123405290008412345
  key0: 123482fQKnspuf123456
